name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create version
        id: create-version
        run: |
          VERSION=v`date +%Y%m%d-%H%M%S`
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "created version tag: $VERSION"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/chrisjpalmer/korean-restaurants:latest,ghcr.io/chrisjpalmer/korean-restaurants:${{ steps.create-version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max